import { CocktailRecipe } from './types'

export const RECIPES: CocktailRecipe[] = [
  {
    slug: 'michelada',
    key: 'michelada',
    emoji: '🍺',
    name: 'Michelada',
    base: 'Cerveza',
    description:
      'La reina de las fiestas mexicanas. Cerveza fría con clamato, limón y chile — el trago más popular en cualquier carne asada.',
    difficulty: 'Fácil',
    time: '2 min',
    glassType: 'Tarro o vaso alto',
    searchTitle: 'Cómo hacer una Michelada mexicana — receta clásica',
    portions: [
      { ingredient: '🍺 Cerveza fría', amount: '1 lata o botella (355 ml)' },
      { ingredient: '🫙 Clamato', amount: '60–90 ml' },
      { ingredient: '🍋 Limón', amount: '1 pieza (el jugo)' },
      { ingredient: '🧂 Sal', amount: 'Al gusto (borde del vaso)' },
      { ingredient: '🫙 Tajín', amount: 'Al gusto' },
      { ingredient: '🌶️ Chile piquín', amount: 'Al gusto' },
    ],
    steps: [
      'Exprime el limón en el vaso y frota el borde con la cáscara.',
      'Mezcla sal y Tajín en un plato y escarca el borde del vaso.',
      'Agrega hielo al vaso.',
      'Vierte el clamato y unas gotas de chile piquín.',
      'Añade la cerveza fría poco a poco para que no espume de más.',
      'Revuelve suavemente y sirve de inmediato.',
    ],
    tip: 'Para una michelada más picosa, agrega unas gotitas de salsa Valentina o Tabasco antes de la cerveza.',
  },
  {
    slug: 'paloma',
    key: 'paloma',
    emoji: '🕊️',
    name: 'Paloma',
    base: 'Tequila',
    description:
      'El coctel de tequila más tomado en México, aunque pocos lo saben. Refrescante, ligero y perfecto para el calor.',
    difficulty: 'Fácil',
    time: '2 min',
    glassType: 'Vaso highball o de agua',
    searchTitle: 'Cómo hacer una Paloma con tequila — receta mexicana',
    portions: [
      { ingredient: '🥃 Tequila blanco', amount: '60 ml (2 oz)' },
      { ingredient: '🧃 Squirt o refresco de toronja', amount: '150 ml' },
      { ingredient: '🍋 Limón', amount: '1 pieza (el jugo)' },
      { ingredient: '🧂 Sal', amount: 'Para el borde' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Frota el borde del vaso con limón y escarca con sal.',
      'Llena el vaso con hielo.',
      'Agrega el tequila.',
      'Exprime el limón encima.',
      'Rellena con Squirt frío.',
      'Revuelve una vez y sirve.',
    ],
    tip: 'Usa tequila blanco (no reposado) para que el sabor de la toronja resalte más.',
  },
  {
    slug: 'charro-negro',
    key: 'charro-negro',
    emoji: '🤠',
    name: 'Charro Negro',
    base: 'Tequila',
    description:
      'El primo mexicano del Cuba Libre. Tequila con Coca Cola y limón — sencillo, rico y siempre disponible en cualquier tiendita.',
    difficulty: 'Fácil',
    time: '1 min',
    glassType: 'Vaso con hielo',
    searchTitle: 'Cómo hacer un Charro Negro — tequila con Coca Cola',
    portions: [
      { ingredient: '🥃 Tequila', amount: '60 ml (2 oz)' },
      { ingredient: '🥤 Coca Cola', amount: '150 ml' },
      { ingredient: '🍋 Limón', amount: '½ pieza (el jugo)' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Llena el vaso con hielo.',
      'Agrega el tequila.',
      'Exprime el limón.',
      'Rellena con Coca Cola fría.',
      'Revuelve suavemente y sirve.',
    ],
    tip: 'Agrega una rodaja de limón como decoración. Si quieres más sabor, usa tequila reposado.',
  },
  {
    slug: 'mezcalina',
    key: 'mezcalina',
    emoji: '🧉',
    name: 'Mezcalina',
    base: 'Mezcal',
    description:
      'Para los que prefieren algo con más carácter. Mezcal con jugo de naranja y limón — ahumado, cítrico y muy mexicano.',
    difficulty: 'Fácil',
    time: '2 min',
    glassType: 'Vaso con hielo',
    searchTitle: 'Cómo hacer una Mezcalina — coctel de mezcal con naranja',
    portions: [
      { ingredient: '🧉 Mezcal', amount: '60 ml (2 oz)' },
      { ingredient: '🍊 Jugo de naranja', amount: '120 ml' },
      { ingredient: '🍋 Limón', amount: '1 pieza (el jugo)' },
      { ingredient: '🧂 Sal', amount: 'Para el borde' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Frota el borde del vaso con limón y escarca con sal.',
      'Agrega hielo al vaso.',
      'Vierte el mezcal.',
      'Agrega el jugo de naranja natural o de caja.',
      'Exprime el limón.',
      'Revuelve y sirve.',
    ],
    tip: 'El jugo de naranja natural hace toda la diferencia. Si puedes, exprímelo al momento.',
  },
  {
    slug: 'cuba-libre',
    key: 'cuba-libre',
    emoji: '🍹',
    name: 'Cuba Libre',
    base: 'Ron',
    description:
      'Clásico sin discusión. Ron con Coca Cola y limón — el trago más conocido del mundo y también uno de los más fáciles.',
    difficulty: 'Fácil',
    time: '1 min',
    glassType: 'Vaso alto con hielo',
    searchTitle: 'Cómo hacer un Cuba Libre — receta clásica con ron',
    portions: [
      { ingredient: '🍹 Ron blanco o dorado', amount: '60 ml (2 oz)' },
      { ingredient: '🥤 Coca Cola', amount: '150 ml' },
      { ingredient: '🍋 Limón', amount: '1 pieza (el jugo)' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Llena el vaso con hielo.',
      'Agrega el ron.',
      'Exprime el limón directamente en el vaso.',
      'Rellena con Coca Cola fría.',
      'Revuelve suavemente con una cuchara o popote.',
    ],
    tip: 'Usa ron dorado para más sabor, o blanco si prefieres algo más ligero. No lo revuelvas de más o perderá las burbujas.',
  },
  {
    slug: 'clamato-preparado',
    key: 'clamato-preparado',
    emoji: '🌶️',
    name: 'Clamato preparado',
    base: 'Sin alcohol',
    description:
      'La opción sin alcohol que no decepciona a nadie. Pepino, chamoy, Tajín y clamato — una botana líquida que todos quieren.',
    difficulty: 'Fácil',
    time: '3 min',
    glassType: 'Vaso alto o tarro',
    searchTitle: 'Cómo hacer Clamato preparado con pepino y chamoy',
    portions: [
      { ingredient: '🫙 Clamato', amount: '250 ml' },
      { ingredient: '🥒 Pepino', amount: '½ pieza (en tiras)' },
      { ingredient: '🍋 Limón', amount: '1 pieza (el jugo)' },
      { ingredient: '🫙 Tajín', amount: 'Al gusto' },
      { ingredient: '🍬 Chamoy', amount: 'Al gusto' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Pela y corta el pepino en tiras largas.',
      'Pon las tiras de pepino dentro del vaso.',
      'Agrega hielo.',
      'Vierte el clamato.',
      'Exprime el limón.',
      'Agrega chamoy y Tajín al gusto.',
      'Revuelve y sirve.',
    ],
    tip: 'Escarcha el borde con chamoy y Tajín para que se vea más bonito y tenga más sabor en cada trago.',
  },
  {
    slug: 'whisky-coke',
    key: 'whisky-coke',
    emoji: '🥃',
    name: 'Whisky con Coke',
    base: 'Whisky',
    description:
      'Simple y efectivo. Whisky con Coca Cola sobre hielo — para los que quieren algo un poco más elegante sin complicarse.',
    difficulty: 'Fácil',
    time: '1 min',
    glassType: 'Vaso rocks con hielo',
    searchTitle: 'Cómo preparar Whisky con Coca Cola — proporciones perfectas',
    portions: [
      { ingredient: '🥃 Whisky', amount: '60 ml (2 oz)' },
      { ingredient: '🥤 Coca Cola', amount: '120–150 ml' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Llena el vaso con hielo.',
      'Agrega el whisky.',
      'Vierte la Coca Cola fría despacio por el borde del vaso.',
      'Revuelve una sola vez y sirve.',
    ],
    tip: 'La proporción clásica es 1:2 (whisky:Coca). Si usas whisky de malta, mejor tomarlo solo o con agua — no desperdicies el sabor con refresco.',
  },
  {
    slug: 'hugo-spritz',
    key: 'hugo-spritz',
    emoji: '🌸',
    name: 'Hugo Spritz',
    base: 'St-Germain + Prosecco',
    description:
      'El cóctel europeo más de moda en México. Ligero, floral y muy refrescante — perfecto para bodas, reuniones al aire libre y cualquier evento que pida algo diferente.',
    difficulty: 'Fácil',
    time: '3 min',
    glassType: 'Copa de vino con hielo',
    searchTitle: 'Cómo hacer un Hugo Spritz con St-Germain — receta fácil',
    portions: [
      { ingredient: '🌸 St-Germain (licor de flor de saúco)', amount: '60 ml (2 oz)' },
      { ingredient: '🍾 Prosecco o cava frío', amount: '90 ml (3 oz)' },
      { ingredient: '💧 Agua mineral con gas', amount: '30 ml (un chorrito)' },
      { ingredient: '🌿 Menta fresca', amount: '4–5 hojas' },
      { ingredient: '🍋 Limón verde', amount: '1 rodaja' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Llena una copa de vino grande con hielo.',
      'Agrega el St-Germain.',
      'Vierte el prosecco o cava frío despacio por el borde para no perder el gas.',
      'Añade un chorrito de agua mineral.',
      'Revuelve muy suavemente una sola vez.',
      'Decora con hojas de menta fresca y una rodaja de limón verde.',
    ],
    tip: 'El St-Germain se consigue en tiendas de vinos y licores o en línea. Si no lo encuentras, búscalo como "licor de flor de saúco". El prosecco puede sustituirse por cualquier cava o vino espumoso seco.',
  },
  {
    slug: 'vampiro',
    key: 'vampiro',
    emoji: '🧛',
    name: 'Vampiro',
    base: 'Tequila',
    description:
      'Una Paloma con más carácter. Tequila con toronja, sangrita y Tajín — el coctel que sorprende a quien no lo conoce.',
    difficulty: 'Medio',
    time: '3 min',
    glassType: 'Vaso highball con hielo',
    searchTitle: 'Cómo hacer un Vampiro con tequila y sangrita',
    portions: [
      { ingredient: '🥃 Tequila blanco', amount: '60 ml (2 oz)' },
      { ingredient: '🧃 Squirt o refresco de toronja', amount: '90 ml' },
      { ingredient: '🧃 Sangrita', amount: '60 ml' },
      { ingredient: '🍋 Limón', amount: '1 pieza (el jugo)' },
      { ingredient: '🫙 Tajín', amount: 'Para el borde' },
      { ingredient: '🧂 Sal', amount: 'Para el borde' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Mezcla sal y Tajín en un plato. Frota el borde del vaso con limón y escarca.',
      'Llena el vaso con hielo.',
      'Agrega el tequila.',
      'Vierte la sangrita.',
      'Agrega el Squirt.',
      'Exprime el limón.',
      'Revuelve suavemente y sirve.',
    ],
    tip: 'La sangrita de botella está bien, pero la casera (tomate, naranja, limón, chile) lleva el vampiro a otro nivel.',
  },
  {
    slug: 'aperol-spritz',
    key: 'aperol-spritz',
    emoji: '🍊',
    name: 'Aperol Spritz',
    base: 'Aperol + Prosecco',
    description:
      'El aperitivo italiano que conquistó el mundo. Amargo, cítrico y con ese color naranja inconfundible — ideal para brunchs, tardes de verano y eventos con onda.',
    difficulty: 'Fácil',
    time: '2 min',
    glassType: 'Copa de vino con hielo',
    searchTitle: 'Cómo hacer un Aperol Spritz — receta clásica italiana',
    portions: [
      { ingredient: '🍊 Aperol', amount: '60 ml (2 oz)' },
      { ingredient: '🍾 Prosecco o cava seco', amount: '90 ml (3 oz)' },
      { ingredient: '💧 Agua mineral con gas', amount: '30 ml (un chorrito)' },
      { ingredient: '🍊 Naranja', amount: '1 rodaja (para decorar)' },
      { ingredient: '🧊 Hielo', amount: 'Al gusto' },
    ],
    steps: [
      'Llena una copa de vino grande con hielo.',
      'Vierte el prosecco o cava frío primero — esto mantiene las burbujas.',
      'Agrega el Aperol.',
      'Añade un chorrito de agua mineral.',
      'Revuelve suavemente una sola vez.',
      'Decora con una rodaja de naranja en el borde de la copa.',
    ],
    tip: 'La receta clásica italiana es 3-2-1: 3 partes prosecco, 2 partes Aperol, 1 parte soda. Siempre agrega el prosecco antes que el Aperol para no perder el gas.',
  },
]

export const RECIPE_MAP = Object.fromEntries(
  RECIPES.map((r) => [r.slug, r])
) as Record<string, CocktailRecipe>
